export JENKINS_URL='http://jenkins.foobar.com'
export JENKINS_USERNAME='pmarlowe'
export JENKINS_PASSWORD='uhoh'
export JENKINS_TEMPLATE_JOB_NAME='pull_request_job_template'
export JENKINS_REMOTE_BUILD_AUTH_TOKEN='hotbaz'
export GITHUB_REPO_OWNER='pmarlowe'
export GITHUB_REPO='the-long-goodbye'
export GITHUB_OAUTH_TOKEN='uhoh!'
